### ISSUE TITLE
picard erro

### ISSUE THREAD

**Issue by zhangfanbaba** [hoechenberger/pybrain_mne#5]
Hello Richard,
In the 04-cleaning_data lab,i'm facing a problem.

In the cell ICA 

n_components = 0.8  # Should normally be higher, like 0.999!!
method = 'picard'
max_iter = 100  # Should normally be higher, like 500 or even 1000!!
fit_params = dict(fastica_it=5)
random_state = 42

ica = mne.preprocessing.ICA(n_components=n_components,
    max_pca_components=300,
                            method=method,
                            max_iter=max_iter,
                            fit_params=fit_params,
                            random_state=random_state)
ica.fit(epochs_ica)

erro:
cannot import name 'picard' from 'picard'(D:\Users\ROG\anaconda3\envs\pytorch\Lib\site-packages\picard\__init__.py)

Can you help me come up with this question,thank you very much!!!!

**Comment by hoechenberger** [comment]
Hello, are you sure you installed Picard via `conda install -c conda-forge python-picard`?

**Comment by zhangfanbaba** [comment]
> Hello, are you sure you installed Picard via `conda install -c conda-forge python-picard`?

Yes, I need to download python-picard, not just picard, I've solved the problem now, thank you very much，Richard！

**Comment by hoechenberger** [comment]
Great to hear it's working now! 👍
